### ISSUE TITLE
ETV subtiitrid puudu

### ISSUE THREAD

**Issue by jeesus** [yllar/yllar-xbmc-repo#1]
Mingi kuu jooksul on ära kadunud ETV pluginal subtiitrid. Enne jooksis Kodi 15.2 peal, aga igaks juhuks proovisin ära ka 16.0, kuid subtiitrid endiselt puudu kõigel. 16.2'ga ei proovinud, aga kahtlustan ETV enda poolset muudatust. Justkui oleks subtiitrite paigutamist muutnud...

Jookseb Win8 peal, vajadusel saan logi ka üles visata.

**Comment by yllar** [comment]
ETV ei keevita subtiitreid enam videosse, vaid paneb need eraldi faili. etv plugina versioonis 0.0.12 võiks nende näitamine töötada.  Subtiitritega video käivitamine võtab kahjuks kauem aega aga sinna pole vist väga midagi parata. Kui see väga häirib, ning subtiitrite olemasolu väga vajalik pole, siis saab nende näitamise (ja laadimise) seadete alt kinni keerata.

**Comment by jeesus** [comment]
Töötab, tänud! Ent vaikimisi laaditakse vist mingi tühi fail. Selleks, et subtiitreid näitaks, peab subtiitrite menüüs valima "Järgmine". Mõnedele eestikeelsetele saadetele (nt Kahekõne) ei näita endiselt subtiitreid. Võimalik, et vene encodingu support puudub vm taolist.

**Comment by yllar** [comment]
Versioonis 0.0.14 lisasin seadete alla keele eelistuse valiku. Kahekõnes oli subtiitrite "keeleks" vaegkuuljad ja seepärast esmane versioon neid ei näidanud. Nüüd saab seadete all valida kaks eelistust ja subtiitrid valitakse vastavale sellele. 

**NB!** kui versioon 0.0.13 alt on seadeid muudetud, siis 0.0.14 peab korraks seadeid muutma ja need salvestama (Vaikeväärtused ja OK). Vastasel korral tuleb saadet avades viga.

Arvutis töötab mul ilusti, kuid Android TV'ga on tõesti nii, et subtiitrite nägemiseks peab vajutama "Järgmine" - vajab uurimist
