### ISSUE TITLE
ETV stream stops

### ISSUE THREAD

**Issue by dyyd** [yllar/yllar-xbmc-repo#2]
Using Kodi 17.6 and ETV add-on 0.0.18
When watching "ETV otse" the stream plays for a few second and then ends and need to restart it. Does not continuously play.

**Comment by jeesus** [comment]
It would help a lot if you enable logging from Kodi's settings. Then play the live stream again. Check in your Kodi folder and upload your log file for analysis.

**Comment by dyyd** [comment]
Here you go, the log file
[kodi.log](https://github.com/yllar/yllar-xbmc-repo/files/2193991/kodi.log)

Should contain 4 or 5 times of starting the stream. Some ran for ~40 seconds, once for about 1 minute and 30 seconds.

Currently running Kodi on a Steamlink but had the same issue on a laptop I was previously using as Kodi machine as well, about a month ago. Sadly don't have that machine at the moment anymore so I can't get the log.

**Comment by ghost** [comment]
I have a same problem on LibreELEC.

**Comment by yllar** [comment]
might be fixed in 0.0.21 :) worked for several minutes
